keys:
  - &users
    - &notoh age1ckvmyqkwk69j64ev3fmckytz6k2dv79z4gn5qf6gxqyevp5yjfesdfkxmn

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *notoh
  - path_regex: secrets/s3/[^/]+\.yaml$
    key_groups:
      - age:
          - *notoh
  - path_regex: secrets/restic/[^/]+\.yaml$
    key_groups:
      - age:
          - *notoh
  - path_regex: secrets/tailscale/[^/]+\.yaml$
    key_groups:
      - age:
          - *notoh
  - path_regex: secrets/runners/[^/]+\.yaml$
    key_groups:
      - age:
          - *notoh
