on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: https://github.com/DeterminateSystems/nix-installer-action@main
        with:
          - github-token: ${{ secrets.GH_TOKEN }}
      - run: nix flake check
