on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nix action
        uses: https://github.com/DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
      - name: update flake.lock
        uses: https://github.com/DeterminateSystems/update-flake-lock@v20
        with:
          pr-title: "flake.lock: Update"
          pr-labels: |
            nix
            dependencies
            automated
