on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nix action
        uses: https://github.com/DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
      - name: update flake.lock
        run: nix flake update
      - name: create PR
        uses: https://github.com/peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN_FOR_UPDATES }}
          committer: forgejo <dev@notohh.dev>
          author: notohh <github@notohh.dev>
