name: deploy systems

on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install nix action
        uses: https://github.com/DeterminateSystems/nix-installer-action@v5
        with:
          github-token: ${{ secrets.GH_TOKEN }}
      - name: deploy
        uses: https://github.com/appleboy/ssh-action@v1.0.0
        with:
          host: "100.121.201.47"
          script: |
            uname -a
